using System.IO;
using Game.Configs.Editor;
using NUnit.Framework;

namespace Game.Configs.Tests.Editor
{
    /// <summary>
    /// The rewrite report is a committed derived artifact — the change journal people read instead of
    /// diffing json. A committed file that is regenerated by hand rots silently, so regeneration must
    /// reproduce it exactly. Same trick the bundled-config parity test uses.
    /// </summary>
    public sealed class BookDescriptionRewriteReportTests
    {
        [Test]
        public void CommittedReport_MatchesAFreshRun()
        {
            var path = BookDescriptionRewriteReport.OutputPath;
            Assert.IsTrue(File.Exists(path), $"{path} not found. Run Tools/Configs/Report Book Descriptions Batch.");

            var committed = Normalize(File.ReadAllText(path));
            var regenerated = Normalize(BookDescriptionRewriteReport.Build());

            Assert.AreEqual(
                regenerated,
                committed,
                $"{path} is out of date. Run Tools/Configs/Report Book Descriptions Batch and commit the result.");
        }

        /// <summary>
        /// Line endings are normalized because git is configured with autocrlf; the content is what matters.
        /// </summary>
        private static string Normalize(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");
    }
}
