using System;
using System.IO;
using System.Linq;
using Game.Configs.Editor;
using NUnit.Framework;

namespace Game.Configs.Tests.Editor
{
    /// <summary>
    /// The rewrite report is a committed derived artifact — the change journal people read instead of
    /// diffing json. A committed file that is regenerated by hand rots silently, so regeneration must
    /// reproduce it exactly. Same trick the bundled-config parity test uses.
    /// </summary>
    public sealed class BookDescriptionRewriteReportTests
    {
        [Test]
        public void CommittedReport_MatchesAFreshRun()
        {
            var expected = BookDescriptionRewriteReport.BuildAll();

            foreach (var file in expected)
            {
                Assert.IsTrue(
                    File.Exists(file.Key),
                    $"{file.Key} is missing. Run Tools/Configs/Report Book Descriptions Batch.");

                Assert.AreEqual(
                    Normalize(file.Value),
                    Normalize(File.ReadAllText(file.Key)),
                    $"{file.Key} is out of date. Run Tools/Configs/Report Book Descriptions Batch and commit the result.");
            }
        }

        /// <summary>
        /// A batch file left behind after its batch was renumbered or dropped keeps describing books that
        /// moved, and nothing else would notice.
        /// </summary>
        [Test]
        public void NoStaleBatchFiles()
        {
            Assert.IsTrue(
                Directory.Exists(BookDescriptionRewriteReport.BatchDirectory),
                $"{BookDescriptionRewriteReport.BatchDirectory} not found.");

            var expected = BookDescriptionRewriteReport.BuildAll().Keys
                .Select(path => Path.GetFileName(path))
                .ToArray();

            var present = Directory
                .GetFiles(
                    BookDescriptionRewriteReport.BatchDirectory,
                    BookDescriptionRewriteReport.BatchFilePrefix + "*.md")
                .Select(Path.GetFileName)
                .ToArray();

            var stale = present.Where(name => !expected.Contains(name, StringComparer.OrdinalIgnoreCase)).ToArray();

            Assert.IsEmpty(
                stale,
                $"Stale batch report(s): {string.Join(", ", stale)}. Re-run Tools/Configs/Report Book Descriptions Batch.");
        }

        /// <summary>
        /// Line endings are normalized because git is configured with autocrlf; the content is what matters.
        /// </summary>
        private static string Normalize(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");
    }
}
