using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Game.Configs.Models;
using Newtonsoft.Json;

namespace Game.Configs.Editor
{
    /// <summary>
    /// The change journal for the book-description rewrite: what the text was, what it became, and what that
    /// did to the writing — globally and per book.
    ///
    /// <para>It is <b>derived</b>, never authored. Storing "book341 lost its joke" in the draft row would be
    /// a lie the moment that row is rewritten; recomputing it from the frozen seed cannot go stale. A test
    /// asserts that regenerating this report reproduces the committed file byte for byte, which is what keeps
    /// the committed copy honest.</para>
    ///
    /// <para>Deliberately contains no timestamp: a generated artifact that changes on every run cannot be
    /// diffed and cannot be tested.</para>
    /// </summary>
    public static class BookDescriptionRewriteReport
    {
        public const string OutputPath = "docs/content/REWRITE_REPORT.md";

        private static readonly Regex SecondPerson =
            new(@"\b(you|your|yours|yourself)\b", RegexOptions.Compiled | RegexOptions.IgnoreCase);

        public static string Build(
            string configsDir = BookDescriptionDraftValidator.ConfigsDir,
            string seedPath = BookDescriptionDraftValidator.SeedPath,
            string draftsPath = BookDescriptionDraftValidator.DraftsPath)
        {
            var books = ReadList<BookConfig>(Path.Combine(configsDir, BookDescriptionDraftValidator.BooksFileName));
            var drafts = ReadList<BookDescriptionDraft>(draftsPath);
            var seed = JsonConvert.DeserializeObject<Dictionary<string, BookDescriptionDraftValidator.SeedEntry>>(
                File.ReadAllText(seedPath));

            var booksById = books.Where(book => book?.Id != null).ToDictionary(book => book.Id, book => book);
            var report = BookDescriptionDraftValidator.Validate(configsDir, seedPath, draftsPath);

            var sb = new StringBuilder();
            AppendHeader(sb);
            AppendOverall(sb, books, drafts, seed, report);
            AppendToneDevices(sb, drafts, seed);
            AppendPerBook(sb, drafts, booksById, seed);

            return sb.ToString();
        }

        private static void AppendHeader(StringBuilder sb)
        {
            Line(sb, "# Book descriptions — rewrite report");
            Line(sb);
            Line(sb, "Generated by `Tools/Configs/Report Book Descriptions Batch`. Do not edit by hand:");
            Line(sb, "`BookDescriptionRewriteReportTests` fails when this file and a fresh run disagree.");
            Line(sb);
            Line(sb, "The text being replaced comes from `book_descriptions_seed_en.json`, the frozen archive of");
            Line(sb, "the seeded catalogue. Writing rules live in `BOOK_DESCRIPTION_STYLE.md`.");
            Line(sb);
        }

        private static void AppendOverall(
            StringBuilder sb,
            IReadOnlyList<BookConfig> books,
            IReadOnlyList<BookDescriptionDraft> drafts,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed,
            BookDescriptionDraftReport report)
        {
            var real = books.Where(book => book != null && !book.IsExcludedFromCatalog).ToList();
            var draftedIds = new HashSet<string>(drafts.Select(draft => draft.Id), StringComparer.OrdinalIgnoreCase);
            var remaining = real.Where(book => !draftedIds.Contains(book.Id)).ToList();

            Line(sb, "## Overall");
            Line(sb);
            Line(sb, $"- seed archive: {seed.Count} rows ({real.Count} in the catalogue, {books.Count - real.Count} excluded)");
            Line(sb, $"- rewritten: {drafts.Count} of {real.Count} catalogue books");
            Line(sb, $"- remaining: {remaining.Count}");
            Line(sb, $"- validator: {report.Errors.Count} error(s), {report.Warnings.Count} warning(s)");

            if (report.NeedsFactCheck.Count > 0)
                Line(sb, $"- written without knowing the book: {string.Join(", ", report.NeedsFactCheck)}");

            Line(sb);
            Line(sb, "By batch and status:");
            Line(sb);
            Line(sb, "| batch | status | books |");
            Line(sb, "|---|---|---|");
            foreach (var group in drafts
                         .GroupBy(draft => (draft.Batch, Status: draft.Status ?? "-"))
                         .OrderBy(group => group.Key.Batch)
                         .ThenBy(group => group.Key.Status, StringComparer.Ordinal))
            {
                Line(sb, $"| {group.Key.Batch} | {group.Key.Status} | {group.Count()} |");
            }

            Line(sb);
            Line(sb, "Remaining by primary genre:");
            Line(sb);
            Line(sb, "| genre | books left |");
            Line(sb, "|---|---|");
            foreach (var group in remaining
                         .GroupBy(book => book.PrimaryGenre ?? "-")
                         .OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                Line(sb, $"| {group.Key} | {group.Count()} |");
            }

            Line(sb);
        }

        /// <summary>
        /// The measurement that drove relaxing the tone: the first pass wrote strict third person and lost
        /// every device the seeded text used to sound warm.
        /// </summary>
        private static void AppendToneDevices(
            StringBuilder sb,
            IReadOnlyList<BookDescriptionDraft> drafts,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed)
        {
            var total = drafts.Count;
            var wasQuestion = 0;
            var wasExclamation = 0;
            var wasSecondPerson = 0;
            var isQuestion = 0;
            var isExclamation = 0;
            var isSecondPerson = 0;

            foreach (var draft in drafts)
            {
                var old = SeedText(seed, draft.Id);
                if (HasQuestion(old)) wasQuestion++;
                if (HasExclamation(old)) wasExclamation++;
                if (HasSecondPerson(old)) wasSecondPerson++;

                if (HasQuestion(draft.New)) isQuestion++;
                if (HasExclamation(draft.New)) isExclamation++;
                if (HasSecondPerson(draft.New)) isSecondPerson++;
            }

            Line(sb, "## Tone devices");
            Line(sb);
            Line(sb, $"Across the {total} rewritten book(s), counted in the text being replaced and in the rewrite.");
            Line(sb, "All three are allowed; strict third person is what made the first pass read dry.");
            Line(sb);
            Line(sb, "| device | seeded | rewritten |");
            Line(sb, "|---|---|---|");
            Line(sb, $"| rhetorical question | {wasQuestion} | {isQuestion} |");
            Line(sb, $"| exclamation | {wasExclamation} | {isExclamation} |");
            Line(sb, $"| addresses the reader | {wasSecondPerson} | {isSecondPerson} |");
            Line(sb);
        }

        private static void AppendPerBook(
            StringBuilder sb,
            IReadOnlyList<BookDescriptionDraft> drafts,
            IReadOnlyDictionary<string, BookConfig> booksById,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed)
        {
            Line(sb, "## Per book");
            Line(sb);

            foreach (var draft in drafts.OrderBy(d => d.Batch).ThenBy(d => SortKey(d.Id), StringComparer.Ordinal))
            {
                var old = SeedText(seed, draft.Id);
                var text = draft.New ?? string.Empty;
                booksById.TryGetValue(draft.Id ?? string.Empty, out var book);

                var genres = book?.Genres == null ? "-" : string.Join(", ", book.Genres);
                var qualities = book?.Qualities == null ? "-" : string.Join(", ", book.Qualities);
                var delta = text.Length - old.Length;
                var shared = BookDescriptionDraftValidator.LongestSharedRun(
                    text, old, new[] { draft.TitleAtDraft, draft.AuthorAtDraft });

                Line(sb, $"### {draft.Id} — {draft.TitleAtDraft} · {draft.AuthorAtDraft}");
                Line(sb);
                Line(sb, $"- batch {draft.Batch}, {draft.Status}"
                         + (draft.Recognized ? string.Empty : ", **written without knowing the book**"));
                Line(sb, $"- genres: {genres}");
                Line(sb, $"- qualities: {qualities}");
                Line(sb, $"- published {book?.Published.ToString(CultureInfo.InvariantCulture) ?? "-"}, "
                         + $"{book?.Pages.ToString(CultureInfo.InvariantCulture) ?? "-"} pages");
                Line(sb, $"- length: {old.Length} -> {text.Length} ({Signed(delta)})");
                Line(sb, $"- longest shared run with the replaced text: {shared} word(s)");
                Line(sb, $"- devices lost: {DeviceDiff(old, text)}");
                Line(sb, $"- devices gained: {DeviceDiff(text, old)}");
                if (!string.IsNullOrWhiteSpace(draft.Notes))
                    Line(sb, $"- note: {draft.Notes}");
                Line(sb);
                Line(sb, $"> **was:** {old}");
                Line(sb);
                Line(sb, $"> **now:** {text}");
                Line(sb);
            }
        }

        // ---------- helpers ----------

        private static string DeviceDiff(string from, string to)
        {
            var lost = new List<string>();
            if (HasQuestion(from) && !HasQuestion(to)) lost.Add("rhetorical question");
            if (HasExclamation(from) && !HasExclamation(to)) lost.Add("exclamation");
            if (HasSecondPerson(from) && !HasSecondPerson(to)) lost.Add("addresses the reader");
            return lost.Count == 0 ? "-" : string.Join(", ", lost);
        }

        private static bool HasQuestion(string text) => !string.IsNullOrEmpty(text) && text.Contains("?");

        private static bool HasExclamation(string text) => !string.IsNullOrEmpty(text) && text.Contains("!");

        private static bool HasSecondPerson(string text)
            => !string.IsNullOrEmpty(text) && SecondPerson.IsMatch(text);

        private static string Signed(int value)
            => value > 0
                ? "+" + value.ToString(CultureInfo.InvariantCulture)
                : value.ToString(CultureInfo.InvariantCulture);

        private static string SeedText(
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed,
            string id)
            => id != null && seed.TryGetValue(id, out var entry) ? entry.Description ?? string.Empty : string.Empty;

        /// <summary>Numeric order, so book9 does not sort after book100 in a report people read top to bottom.</summary>
        private static string SortKey(string id)
        {
            if (string.IsNullOrEmpty(id)) return string.Empty;
            var digits = new string(id.Where(char.IsDigit).ToArray());
            return int.TryParse(digits, out var number) ? number.ToString("D6", CultureInfo.InvariantCulture) : id;
        }

        private static List<T> ReadList<T>(string path)
            => JsonConvert.DeserializeObject<List<T>>(File.ReadAllText(path.Replace('\\', '/'))) ?? new List<T>();

        // Explicit '\n': the report is committed and compared byte for byte, so it must not depend on
        // Environment.NewLine or on git's autocrlf.
        private static void Line(StringBuilder sb, string text = "") => sb.Append(text).Append('\n');
    }
}
