using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Game.Configs.Models;
using Newtonsoft.Json;

namespace Game.Configs.Editor
{
    /// <summary>
    /// The change journal for the book-description rewrite: what the text was, what it became, and what that
    /// did to the writing — globally and per book.
    ///
    /// <para>It is <b>derived</b>, never authored. Storing "book341 lost its joke" in the draft row would be
    /// a lie the moment that row is rewritten; recomputing it from the frozen seed cannot go stale. A test
    /// asserts that regenerating reproduces the committed files byte for byte, which is what keeps them honest.</para>
    ///
    /// <para>Split in two on purpose: a one-page summary plus one file per batch. The per-book sections run
    /// about 800 bytes a book, so a single file would pass 400 KB across the catalogue and every batch would
    /// rewrite all of it — a diff nobody can read, which is how a generated artifact stops being reviewed.</para>
    ///
    /// <para>Deliberately contains no timestamp: an artifact that changes on every run cannot be diffed and
    /// cannot be tested.</para>
    /// </summary>
    public static class BookDescriptionRewriteReport
    {
        public const string SummaryPath = "docs/content/REWRITE_REPORT.md";
        public const string BatchDirectory = "docs/content/batches";
        public const string BatchFilePrefix = "REWRITE_REPORT_batch_";

        private static readonly Regex SecondPerson =
            new(@"\b(you|your|yours|yourself)\b", RegexOptions.Compiled | RegexOptions.IgnoreCase);

        private static readonly Regex Word = new(@"[A-Za-z']+", RegexOptions.Compiled);

        public static string BatchPath(int batch)
            => $"{BatchDirectory}/{BatchFilePrefix}{batch.ToString("D2", CultureInfo.InvariantCulture)}.md";

        /// <summary>
        /// Every file the journal consists of, keyed by path. The caller writes them; the test compares them.
        /// </summary>
        public static IReadOnlyDictionary<string, string> BuildAll(
            string configsDir = BookDescriptionDraftValidator.ConfigsDir,
            string seedPath = BookDescriptionDraftValidator.SeedPath,
            string draftsPath = BookDescriptionDraftValidator.DraftsPath)
        {
            var books = ReadList<BookConfig>(Path.Combine(configsDir, BookDescriptionDraftValidator.BooksFileName));
            var drafts = ReadList<BookDescriptionDraft>(draftsPath);
            var seed = JsonConvert.DeserializeObject<Dictionary<string, BookDescriptionDraftValidator.SeedEntry>>(
                File.ReadAllText(seedPath));

            var booksById = books.Where(book => book?.Id != null).ToDictionary(book => book.Id, book => book);
            var report = BookDescriptionDraftValidator.Validate(configsDir, seedPath, draftsPath);

            var batches = drafts
                .GroupBy(draft => draft.Batch)
                .OrderBy(group => group.Key)
                .ToList();

            var files = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                [SummaryPath] = BuildSummary(books, drafts, seed, report, batches)
            };

            foreach (var batch in batches)
                files[BatchPath(batch.Key)] = BuildBatchFile(batch.Key, batch.ToList(), booksById, seed);

            return files;
        }

        // ---------- summary ----------

        private static string BuildSummary(
            IReadOnlyList<BookConfig> books,
            IReadOnlyList<BookDescriptionDraft> drafts,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed,
            BookDescriptionDraftReport report,
            IReadOnlyList<IGrouping<int, BookDescriptionDraft>> batches)
        {
            var sb = new StringBuilder();

            Line(sb, "# Book descriptions — rewrite report");
            Line(sb);
            Line(sb, "Generated by `Tools/Configs/Report Book Descriptions Batch`. Do not edit by hand:");
            Line(sb, "`BookDescriptionRewriteReportTests` fails when these files and a fresh run disagree.");
            Line(sb);
            Line(sb, "The text being replaced comes from `book_descriptions_seed_en.json`, the frozen archive of");
            Line(sb, "the seeded catalogue. Writing rules live in `BOOK_DESCRIPTION_STYLE.md`. Per-book changes");
            Line(sb, "are in the batch files linked below.");
            Line(sb);

            var real = books.Where(book => book != null && !book.IsExcludedFromCatalog).ToList();
            var draftedIds = new HashSet<string>(drafts.Select(draft => draft.Id), StringComparer.OrdinalIgnoreCase);
            var remaining = real.Where(book => !draftedIds.Contains(book.Id)).ToList();

            Line(sb, "## Overall");
            Line(sb);
            Line(sb, $"- seed archive: {seed.Count} rows ({real.Count} in the catalogue, {books.Count - real.Count} excluded)");
            Line(sb, $"- rewritten: {drafts.Count} of {real.Count} catalogue books");
            Line(sb, $"- remaining: {remaining.Count}");
            Line(sb, $"- validator: {report.Errors.Count} error(s), {report.Warnings.Count} warning(s)");
            if (report.NeedsFactCheck.Count > 0)
                Line(sb, $"- written without knowing the book: {string.Join(", ", report.NeedsFactCheck)}");
            Line(sb);

            Line(sb, "## Batches");
            Line(sb);
            Line(sb, "| batch | books | statuses | detail |");
            Line(sb, "|---|---|---|---|");
            foreach (var batch in batches)
            {
                var statuses = string.Join(
                    ", ",
                    batch.GroupBy(draft => draft.Status ?? "-")
                        .OrderBy(group => group.Key, StringComparer.Ordinal)
                        .Select(group => $"{group.Key} {group.Count()}"));
                var fileName = Path.GetFileName(BatchPath(batch.Key));
                Line(sb, $"| {batch.Key} | {batch.Count()} | {statuses} | [batches/{fileName}](batches/{fileName}) |");
            }

            Line(sb);

            // Per batch, not in aggregate: an aggregate hides a batch that came back in flat third person,
            // which is exactly the mistake the first pass made across all 42 books at once.
            Line(sb, "## Tone devices by batch");
            Line(sb);
            Line(sb, "All three are allowed and wanted; strict third person is what made the first pass read dry.");
            Line(sb, "`seeded` counts the same books in the text being replaced, as the baseline.");
            Line(sb);
            Line(sb, "| batch | rhetorical question | exclamation | addresses the reader |");
            Line(sb, "|---|---|---|---|");
            foreach (var batch in batches)
            {
                var rows = batch.ToList();
                Line(sb, $"| {batch.Key} | {Device(rows, seed, HasQuestion)} | {Device(rows, seed, HasExclamation)} "
                         + $"| {Device(rows, seed, HasSecondPerson)} |");
            }

            Line(sb);
            Line(sb, "## Remaining by primary genre");
            Line(sb);
            Line(sb, "| genre | books left |");
            Line(sb, "|---|---|");
            foreach (var group in remaining
                         .GroupBy(book => book.PrimaryGenre ?? "-")
                         .OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                Line(sb, $"| {group.Key} | {group.Count()} |");
            }

            Line(sb);
            return sb.ToString();
        }

        private static string Device(
            IReadOnlyList<BookDescriptionDraft> rows,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed,
            Func<string, bool> has)
        {
            var seeded = rows.Count(row => has(SeedText(seed, row.Id)));
            var rewritten = rows.Count(row => has(row.New));
            return $"{rewritten} (seeded {seeded})";
        }

        // ---------- per batch ----------

        private static string BuildBatchFile(
            int batch,
            IReadOnlyList<BookDescriptionDraft> rows,
            IReadOnlyDictionary<string, BookConfig> booksById,
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed)
        {
            var sb = new StringBuilder();

            Line(sb, $"# Rewrite batch {batch.ToString(CultureInfo.InvariantCulture)}");
            Line(sb);
            Line(sb, "Generated — see [../REWRITE_REPORT.md](../REWRITE_REPORT.md). Do not edit by hand.");
            Line(sb);
            Line(sb, $"- books: {rows.Count}");
            Line(sb, $"- tone devices: rhetorical question {rows.Count(row => HasQuestion(row.New))}, "
                     + $"exclamation {rows.Count(row => HasExclamation(row.New))}, "
                     + $"addresses the reader {rows.Count(row => HasSecondPerson(row.New))}");

            // Uniform openings are the most visible sign of generated copy, and the only way to see it is
            // to count: the first pass opened 16 of 42 descriptions with "A".
            Line(sb, $"- most common openings: {OpeningWords(rows)}");
            Line(sb);

            foreach (var draft in rows.OrderBy(row => SortKey(row.Id), StringComparer.Ordinal))
            {
                var old = SeedText(seed, draft.Id);
                var text = draft.New ?? string.Empty;
                booksById.TryGetValue(draft.Id ?? string.Empty, out var book);

                var genres = book?.Genres == null ? "-" : string.Join(", ", book.Genres);
                var qualities = book?.Qualities == null ? "-" : string.Join(", ", book.Qualities);
                var shared = BookDescriptionDraftValidator.LongestSharedRun(
                    text, old, new[] { draft.TitleAtDraft, draft.AuthorAtDraft });

                Line(sb, $"### {draft.Id} — {draft.TitleAtDraft} · {draft.AuthorAtDraft}");
                Line(sb);
                Line(sb, $"- {draft.Status}" + (draft.Recognized ? string.Empty : ", **written without knowing the book**"));
                Line(sb, $"- genres: {genres}");
                Line(sb, $"- qualities: {qualities}");
                Line(sb, $"- published {book?.Published.ToString(CultureInfo.InvariantCulture) ?? "-"}, "
                         + $"{book?.Pages.ToString(CultureInfo.InvariantCulture) ?? "-"} pages");
                Line(sb, $"- length: {old.Length} -> {text.Length} ({Signed(text.Length - old.Length)})");
                Line(sb, $"- longest shared run with the replaced text: {shared} word(s)");
                Line(sb, $"- devices lost: {DeviceDiff(old, text)}");
                Line(sb, $"- devices gained: {DeviceDiff(text, old)}");
                if (!string.IsNullOrWhiteSpace(draft.Notes))
                    Line(sb, $"- note: {draft.Notes}");
                Line(sb);
                Line(sb, $"> **was:** {old}");
                Line(sb);
                Line(sb, $"> **now:** {text}");
                Line(sb);
            }

            return sb.ToString();
        }

        private static string OpeningWords(IReadOnlyList<BookDescriptionDraft> rows)
        {
            var counts = new Dictionary<string, int>(StringComparer.Ordinal);

            foreach (var row in rows)
            {
                var match = Word.Match(row.New ?? string.Empty);
                if (!match.Success) continue;

                counts.TryGetValue(match.Value, out var seen);
                counts[match.Value] = seen + 1;
            }

            var top = counts
                .OrderByDescending(pair => pair.Value)
                .ThenBy(pair => pair.Key, StringComparer.Ordinal)
                .Take(5)
                .Select(pair => $"{pair.Key} x{pair.Value}")
                .ToArray();

            return top.Length == 0 ? "-" : string.Join(", ", top);
        }

        // ---------- helpers ----------

        private static string DeviceDiff(string from, string to)
        {
            var lost = new List<string>();
            if (HasQuestion(from) && !HasQuestion(to)) lost.Add("rhetorical question");
            if (HasExclamation(from) && !HasExclamation(to)) lost.Add("exclamation");
            if (HasSecondPerson(from) && !HasSecondPerson(to)) lost.Add("addresses the reader");
            return lost.Count == 0 ? "-" : string.Join(", ", lost);
        }

        private static bool HasQuestion(string text) => !string.IsNullOrEmpty(text) && text.Contains("?");

        private static bool HasExclamation(string text) => !string.IsNullOrEmpty(text) && text.Contains("!");

        private static bool HasSecondPerson(string text)
            => !string.IsNullOrEmpty(text) && SecondPerson.IsMatch(text);

        private static string Signed(int value)
            => value > 0
                ? "+" + value.ToString(CultureInfo.InvariantCulture)
                : value.ToString(CultureInfo.InvariantCulture);

        private static string SeedText(
            IReadOnlyDictionary<string, BookDescriptionDraftValidator.SeedEntry> seed,
            string id)
            => id != null && seed.TryGetValue(id, out var entry) ? entry.Description ?? string.Empty : string.Empty;

        /// <summary>Numeric order, so book9 does not sort after book100 in a file people read top to bottom.</summary>
        private static string SortKey(string id)
        {
            if (string.IsNullOrEmpty(id)) return string.Empty;
            var digits = new string(id.Where(char.IsDigit).ToArray());
            return int.TryParse(digits, out var number) ? number.ToString("D6", CultureInfo.InvariantCulture) : id;
        }

        private static List<T> ReadList<T>(string path)
            => JsonConvert.DeserializeObject<List<T>>(File.ReadAllText(path.Replace('\\', '/'))) ?? new List<T>();

        // Explicit '\n': these files are committed and compared byte for byte, so they must not depend on
        // Environment.NewLine or on git's autocrlf.
        private static void Line(StringBuilder sb, string text = "") => sb.Append(text).Append('\n');
    }
}
